#!/usr/bin/env bash
# Fetch the ONNX Runtime iOS XCFramework from Microsoft's public CDN and
# stage its static archives where ort-sys' build script can find them.
#
# Microsoft ships iOS via CocoaPods + a public CDN download (the same URL
# the `onnxruntime-c` podspec points at). We pull straight from the CDN to
# avoid round-tripping through a synthetic Xcode project just to drive
# `pod install`. Once `tauri ios init` generates a real iOS project we can
# also wire onnxruntime-c as a proper Pod dependency at the app layer — but
# the Rust build needs the static libs ahead of that.
#
# Output layout (read by `.cargo/config.toml`):
#   vendor/ort-ios/
#     ios-arm64/libonnxruntime.a                 (real device)
#     ios-arm64_x86_64-simulator/libonnxruntime.a (simulator universal)
#
# Pin to ORT 1.20.x: matches `ort 2.0.0-rc.10`'s ORT_API_VERSION == 22.

set -euo pipefail

# The ort 2.0.0-rc.10 bindings demand OrtApi version 22 at runtime. ORT 1.20.0
# only provides up to v20; 1.21.0 provides v22. We pin 1.21.0 on the CDN.
ORT_VERSION="${ORT_VERSION:-1.22.0}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR="$ROOT/vendor/ort-ios"
WORK="$ROOT/.cache/ort-ios"

mkdir -p "$VENDOR" "$WORK"
cd "$WORK"

ZIP="pod-archive-onnxruntime-c-${ORT_VERSION}.zip"
URL="https://download.onnxruntime.ai/${ZIP}"

if [ ! -f "$ZIP" ]; then
  echo "→ downloading $URL"
  curl -fL --progress-bar -o "$ZIP" "$URL"
else
  echo "→ using cached $WORK/$ZIP"
fi

EXTRACT="$WORK/extract-$ORT_VERSION"
rm -rf "$EXTRACT"
mkdir -p "$EXTRACT"
echo "→ unzipping into $EXTRACT"
unzip -q "$ZIP" -d "$EXTRACT"

XCFW=$(find "$EXTRACT" -type d -name "onnxruntime.xcframework" | head -1)
if [ -z "$XCFW" ]; then
  echo "ERROR: onnxruntime.xcframework not found in $EXTRACT"
  exit 1
fi
echo "→ xcframework: $XCFW"

# Each slice's framework contains a static archive named `onnxruntime`
# (no `lib` prefix, no `.a` suffix). ort-sys looks for `libonnxruntime.a`.
for SLICE in ios-arm64 ios-arm64_x86_64-simulator; do
  SRC="$XCFW/$SLICE/onnxruntime.framework/onnxruntime"
  if [ ! -f "$SRC" ]; then
    echo "  WARN: slice $SLICE missing, skipping"
    continue
  fi
  DST="$VENDOR/$SLICE"
  rm -rf "$DST"
  mkdir -p "$DST"
  # Apple ships fat (universal) archives. rustc's archive reader rejects fat
  # ar files ("Unsupported archive identifier"), so split into thin slices.
  ARCHS=$(lipo -archs "$SRC" 2>/dev/null || echo "")
  if [[ "$ARCHS" == *" "* ]] || [[ "$ARCHS" == *","* ]]; then
    # Universal — thin per architecture into named files for cargo to pick.
    for ARCH in $ARCHS; do
      lipo "$SRC" -thin "$ARCH" -output "$DST/libonnxruntime.a.$ARCH"
    done
    # Default `libonnxruntime.a` = arm64 thin (what aarch64-apple-ios-sim wants
    # on Apple Silicon hosts). For x86_64 sim builds the cargo config can
    # override the file copy if ever needed.
    if [ -f "$DST/libonnxruntime.a.arm64" ]; then
      cp "$DST/libonnxruntime.a.arm64" "$DST/libonnxruntime.a"
    else
      cp "$DST/libonnxruntime.a.x86_64" "$DST/libonnxruntime.a"
    fi
  else
    # Single-arch — copy as-is.
    cp -f "$SRC" "$DST/libonnxruntime.a"
  fi
  echo "  staged $SLICE  ($(ls -lh "$DST/libonnxruntime.a" | awk '{print $5}'), archs: $ARCHS)"
done

# Stash the full xcframework too — it'll be linked into the iOS app bundle
# by Xcode once `tauri ios init` has generated the project.
rm -rf "$VENDOR/onnxruntime.xcframework"
cp -R "$XCFW" "$VENDOR/onnxruntime.xcframework"
echo "→ full xcframework copied to $VENDOR/onnxruntime.xcframework"
# Write the absolute paths into .cargo/config.toml so cargo's per-target env
# resolves to the right slice without the user needing to export anything.
# Cargo's `[target.X.env]` only accepts plain strings (no { value=..., relative=true }
# table), so absolute paths are the simplest robust choice. Re-running this
# script regenerates them — safe if the repo gets moved or vendor wiped.
mkdir -p "$ROOT/.cargo"
cat > "$ROOT/.cargo/config.toml" <<EOF
# Generated by scripts/fetch-ort-ios.sh — regenerate by re-running that script.
# Points ORT_LIB_LOCATION at the vendored ONNX Runtime static archive for each
# iOS target. ORT_SKIP_DOWNLOAD=1 tells ort-sys not to attempt a CDN pull.

[target.aarch64-apple-ios.env]
ORT_LIB_LOCATION = "$VENDOR/ios-arm64"
ORT_SKIP_DOWNLOAD = "1"

[target.aarch64-apple-ios-sim.env]
ORT_LIB_LOCATION = "$VENDOR/ios-arm64_x86_64-simulator"
ORT_SKIP_DOWNLOAD = "1"

[target.x86_64-apple-ios.env]
ORT_LIB_LOCATION = "$VENDOR/ios-arm64_x86_64-simulator"
ORT_SKIP_DOWNLOAD = "1"
EOF
echo "→ wrote $ROOT/.cargo/config.toml with absolute ORT_LIB_LOCATION paths"
echo
echo "✓ ORT iOS vendored under $VENDOR"
